# Generated by Django 2.2.3 on 2019-07-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autohunt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='extra_notes',
            field=models.TextField(default='notes'),
            preserve_default=False,
        ),
    ]
