# Generated by Django 2.2.3 on 2019-07-29 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autohunt', '0002_room_extra_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='extra_notes',
        ),
    ]
