# Generated by Django 2.2.3 on 2019-07-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autohunt', '0003_remove_room_extra_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='exitE',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='exitN',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='exitS',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='exitW',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
