# Generated by Django 2.2.3 on 2019-07-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autohunt', '0004_auto_20190729_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='elevation',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='terrain',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
