# Generated by Django 2.2.3 on 2019-07-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autohunt', '0005_auto_20190729_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='cooldown',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='errors',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='room',
            name='items',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='room',
            name='messages',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='room',
            name='players',
            field=models.TextField(blank=True),
        ),
    ]
