# Generated by Django 2.2.3 on 2019-08-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autohunt', '0006_auto_20190730_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('api_key', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('cooldown', models.IntegerField(null=True)),
                ('encumbrance', models.IntegerField(null=True)),
                ('strength', models.IntegerField(null=True)),
                ('speed', models.IntegerField(null=True)),
                ('gold', models.IntegerField(null=True)),
                ('inventory', models.TextField(blank=True)),
                ('status', models.TextField(blank=True)),
                ('errors', models.TextField(blank=True)),
                ('messages', models.TextField(blank=True)),
            ],
        ),
    ]
