# Generated by Django 2.2.3 on 2019-08-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autohunt', '0007_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_room',
            field=models.IntegerField(null=True),
        ),
    ]
