# Generated by Django 2.2.3 on 2019-08-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autohunt', '0008_player_current_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='has_mined',
            field=models.BooleanField(null=True),
        ),
    ]
